# Generated by Django 4.2.30 on 2026-07-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvenomationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('district_hospital', 'District Hospital'), ('health_center', 'Health Center'), ('chps', 'CHPS')], max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('antivenom_available', models.BooleanField(default=False)),
                ('antivenom_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_stock_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient_age_group', models.CharField(max_length=50)),
                ('severity_score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('recommended_action', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('body_system', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='snakebite_s_slug_4a2698_idx'), models.Index(fields=['body_system'], name='snakebite_s_body_sy_94ca07_idx')],
            },
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(max_length=150)),
                ('venom_type', models.CharField(choices=[('hemotoxic', 'Hemotoxic'), ('neurotoxic', 'Neurotoxic'), ('cytotoxic', 'Cytotoxic')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('visual_features', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='snakes/')),
                ('region_distribution', models.ManyToManyField(blank=True, related_name='snakes', to='snakebite.region')),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='snakebite_r_name_f1ac69_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['code'], name='snakebite_r_code_7c69f3_idx'),
        ),
        migrations.AddField(
            model_name='patientassessment',
            name='predicted_envenomation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_assessments', to='snakebite.envenomationtype'),
        ),
        migrations.AddField(
            model_name='patientassessment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_assessments', to='snakebite.region'),
        ),
        migrations.AddField(
            model_name='patientassessment',
            name='symptoms_present',
            field=models.ManyToManyField(blank=True, related_name='patient_assessments', to='snakebite.symptom'),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_facilities', to='snakebite.region'),
        ),
        migrations.AddField(
            model_name='envenomationtype',
            name='associated_symptoms',
            field=models.ManyToManyField(blank=True, related_name='envenomation_types', to='snakebite.symptom'),
        ),
        migrations.AddField(
            model_name='envenomationtype',
            name='target_snakes',
            field=models.ManyToManyField(blank=True, related_name='envenomation_types', to='snakebite.snake'),
        ),
        migrations.AddIndex(
            model_name='snake',
            index=models.Index(fields=['common_name'], name='snakebite_s_common__409aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='snake',
            index=models.Index(fields=['scientific_name'], name='snakebite_s_scienti_69e1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='snake',
            index=models.Index(fields=['venom_type'], name='snakebite_s_venom_t_c91645_idx'),
        ),
        migrations.AddIndex(
            model_name='patientassessment',
            index=models.Index(fields=['timestamp'], name='snakebite_p_timesta_bc1009_idx'),
        ),
        migrations.AddIndex(
            model_name='patientassessment',
            index=models.Index(fields=['region'], name='snakebite_p_region__899a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientassessment',
            index=models.Index(fields=['patient_age_group'], name='snakebite_p_patient_41d03d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientassessment',
            index=models.Index(fields=['risk_level'], name='snakebite_p_risk_le_48e2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='patientassessment',
            index=models.Index(fields=['severity_score'], name='snakebite_p_severit_affdda_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['facility_type'], name='snakebite_h_facilit_c22c38_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['region'], name='snakebite_h_region__ee889e_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['antivenom_available'], name='snakebite_h_antiven_97a26d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['last_stock_update'], name='snakebite_h_last_st_5ea316_idx'),
        ),
        migrations.AddIndex(
            model_name='envenomationtype',
            index=models.Index(fields=['type_name'], name='snakebite_e_type_na_052cab_idx'),
        ),
    ]
