# Generated by Django 4.2.30 on 2026-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('do_statement', models.TextField()),
                ('dont_statement', models.TextField()),
                ('icon_name', models.CharField(blank=True, max_length=80)),
                ('target_audience', models.CharField(choices=[('first_responder', 'First Responder'), ('health_worker', 'Health Worker')], max_length=30)),
            ],
            options={
                'ordering': ['step_number'],
                'indexes': [models.Index(fields=['step_number'], name='snakebite_f_step_nu_743c58_idx'), models.Index(fields=['target_audience'], name='snakebite_f_target__e5408b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('guideline', 'Guideline'), ('poster', 'Poster'), ('video', 'Video'), ('training', 'Training')], max_length=20)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='education/files/')),
                ('video_url', models.URLField(blank=True)),
                ('payload_body', models.TextField(blank=True)),
                ('downloaded_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category'], name='snakebite_e_categor_460731_idx'), models.Index(fields=['downloaded_count'], name='snakebite_e_downloa_029ed5_idx')],
            },
        ),
    ]
