# Generated by Django 4.2.30 on 2026-08-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakebite', '0002_firstaidstep_educationalmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='female', max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('symptoms', models.TextField(blank=True)),
                ('suspected_snake_type', models.CharField(default='Viper (Likely)', max_length=80)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_transit', 'In Transit'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('clinical_notes', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('shared_patient_details', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='snakebite.patientcase')),
                ('destination_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='snakebite.healthfacility')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['case_id'], name='snakebite_p_case_id_aa5c85_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['risk_level'], name='snakebite_p_risk_le_6e726b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['status'], name='snakebite_p_status_107a09_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['created_at'], name='snakebite_p_created_43adea_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='snakebite_r_status_22ea7b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['sent_at'], name='snakebite_r_sent_at_059bd4_idx'),
        ),
    ]
