# Generated by Django 4.2.30 on 2026-08-14 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snakebite', '0003_patientcase_referral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='English', max_length=50)),
                ('alert_radius', models.CharField(default='500m', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snakebite_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='SnakeSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sightings/')),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=200)),
                ('was_bitten', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('time_seen', models.CharField(choices=[('just_now', 'Just now'), ('earlier_today', 'Earlier today'), ('past_week', 'Past week')], default='just_now', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspected_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='snakebite.snake')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='snakebite_s_created_2c1270_idx'), models.Index(fields=['was_bitten'], name='snakebite_s_was_bit_5659fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('medical', 'Medical Provider'), ('handler', 'Snake Handler')], max_length=20)),
                ('organization_or_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_registrations', to='snakebite.region')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_type'], name='snakebite_p_provide_a91525_idx'), models.Index(fields=['region'], name='snakebite_p_region__831fa9_idx')],
            },
        ),
    ]
