# Generated by Django 4.2.30 on 2026-08-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakebite', '0005_patientcase_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='photo',
        ),
        migrations.DeleteModel(
            name='ProviderRegistration',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
