# Generated by Django 4.2.30 on 2026-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebite', '0006_remove_usersettings_user_remove_patientcase_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cases/'),
        ),
    ]
